version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es-single
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    container_name: filebeat
    depends_on:
      - elasticsearch
    user: root
    command: ["--strict.perms=false"]
    volumes:
      # Config do filebeat
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

      - ../logs:/var/log/airflow:ro

      # Artefatos do dbt (seu caminho real)
      - /home/$USER/Projetos/Warehouse_DBT/airflow:/var/dbt:ro

volumes:
  es-data:
